language: node_js

node_js:
  - "6"
  - "5"
  - "4"

cache:
  directories:
    - "node_modules"
    - "typings"

before_install:
  - npm i -g tslint typings
  - typings i

script:
  - npm i
  - sed -i 's/tracerLogger.submit()/ /g' node_modules/apollo-server/dist/apolloServer.js
  - npm test

after_success:
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash)
